# Generated by Django 3.2.7 on 2021-09-24 10:20

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='office',
            name='country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
        migrations.AlterField(
            model_name='person',
            name='location',
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
